# Generated by Django 6.0.1 on 2026-01-29 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_filiere_alter_classe_options_alter_eleve_options_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['nom', 'prenom']},
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_embauche',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='attendance.filiere'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('instructeur', 'Instructeur'), ('responsable_filiere', 'Responsable de Filière'), ('administrateur', 'Administrateur')], default='instructeur', max_length=30),
        ),
    ]
