# Generated by Django 6.0.1 on 2026-04-06 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_matiere_presence_matiere'),
        ('core', '0002_alter_utilisateur_options_utilisateur_actif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='filiere',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='filieres',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='attendance.filiere'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_embauche',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
