# Generated by Django 6.0.1 on 2026-01-29 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rapport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type_filiere', models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('bts', 'BTS'), ('autre', 'Autre')], max_length=20)),
                ('duree', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'verbose_name': 'Classe (Legacy)', 'verbose_name_plural': 'Classes (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='eleve',
            options={'verbose_name': 'Élève (Legacy)', 'verbose_name_plural': 'Élèves (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['-date', '-heure'], 'verbose_name': 'Présence', 'verbose_name_plural': 'Présences'},
        ),
        migrations.AlterModelOptions(
            name='rapport',
            options={'ordering': ['-date_generation']},
        ),
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(choices=[(1, 'Année 1'), (2, 'Année 2'), (3, 'Année 3')])),
                ('annee_academique', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annees_responsables', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annees', to='attendance.filiere')),
            ],
            options={
                'verbose_name': 'Année',
                'verbose_name_plural': 'Années',
                'ordering': ['filiere', 'numero'],
                'unique_together': {('filiere', 'numero', 'annee_academique')},
            },
        ),
        migrations.AddField(
            model_name='presence',
            name='annee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='attendance.annee'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='annee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='attendance.annee'),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_naissance', models.DateField()),
                ('photo', models.ImageField(blank=True, upload_to='etudiants_photos/')),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='attendance.annee')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='attendance.filiere')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presence',
            name='etudiant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='attendance.etudiant'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('etudiant', 'date')},
        ),
        migrations.AddField(
            model_name='rapport',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='attendance.filiere'),
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('type_groupe', models.CharField(choices=[('cm', 'Cours Magistral'), ('td', 'Travaux Dirigés'), ('tp', 'Travaux Pratiques'), ('autre', 'Autre')], default='cm', max_length=20)),
                ('capacite', models.IntegerField(default=30)),
                ('salle', models.CharField(blank=True, max_length=50)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes', to='attendance.annee')),
                ('instructeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_instruire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['annee', 'nom'],
                'unique_together': {('annee', 'code')},
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='attendance.groupe'),
        ),
        migrations.AddField(
            model_name='presence',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences', to='attendance.groupe'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='attendance.groupe'),
        ),
        migrations.RemoveField(
            model_name='presence',
            name='eleve',
        ),
        migrations.AlterUniqueTogether(
            name='etudiant',
            unique_together={('matricule',)},
        ),
    ]
