# Generated by Django 6.0.1 on 2026-04-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_matiere_presence_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='filiere',
        ),
        migrations.AddField(
            model_name='matiere',
            name='filieres',
            field=models.ManyToManyField(related_name='matieres', to='attendance.filiere'),
        ),
    ]
