# Generated by Django 6.0.1 on 2026-04-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_matiere_filiere_matiere_filieres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiant',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='etudiant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.groupe'),
        ),
    ]
