# Generated by Django 6.0.1 on 2026-04-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_etudiant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='etudiants/%Y/%m/'),
        ),
    ]
